# Generated by Django 4.1a1 on 2022-06-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_publication_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrecord",
            name="reading_state",
            field=models.CharField(
                choices=[("wr", "want to read"), ("rg", "reading"), ("rd", "read")],
                max_length=2,
            ),
        ),
        migrations.AddConstraint(
            model_name="bookrecord",
            constraint=models.UniqueConstraint(
                fields=("book", "reader"), name="unique_book_record_for_user"
            ),
        ),
    ]
