# Generated by Django 4.1.3 on 2022-11-21 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_book_favorited_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookreview",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
